// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeekQ.MyConnections.Api.Infrastructure;

namespace SeekQ.MyConnections.Api.Migrations
{
    [DbContext(typeof(MyConnectionsDbContext))]
    partial class MyConnectionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SeekQ.MyConnections.Api.Domain.ConnectionsAggregate.Connection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Blocked")
                        .HasColumnType("bit");

                    b.Property<int>("ConnectionAge")
                        .HasColumnType("int")
                        .HasMaxLength(3);

                    b.Property<string>("ConnectionAvatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ConnectionFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("ConnectionIsAgeVisible")
                        .HasColumnType("bit");

                    b.Property<bool>("ConnectionIsAvatar")
                        .HasColumnType("bit");

                    b.Property<bool>("ConnectionIsFirstNameVisible")
                        .HasColumnType("bit");

                    b.Property<bool>("ConnectionIsLastNameVisible")
                        .HasColumnType("bit");

                    b.Property<string>("ConnectionLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ConnectionNickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<Guid>("ConnectionUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdUser", "ConnectionUserId")
                        .IsUnique();

                    b.ToTable("Connections");
                });
#pragma warning restore 612, 618
        }
    }
}
